### ISSUE TITLE
File system error for checkpointing file

### ISSUE THREAD

**Issue by jdakka** [hengma1001/CVAE_pilot_MD#4]
The `jsrun` command I am using is:

```
jsrun --erf_input /ccs/home/jdakka/radical.pilot.sandbox/re.session.login4.jdakka.017970.0003/pilot.0000/unit.000000//unit.000000.rs --smpiargs="off" python "run_openmm.py" "-f" "/gpfs/alpine/scratch/jdakka/bip178/benchmarks/MD_exps/fs-pep/pdb/100-fs-peptide-400K.pdb" 
```

I get an error:

```
Traceback (most recent call last):
  File "run_openmm.py", line 41, in <module>
    sim_time=10000*u.nanoseconds)
  File "../MD_utils/openmm_simulation.py", line 232, in openmm_simulate_amber_fs_pep
    simulation.step(nsteps)
  File "/ccs/home/jdakka/.conda/envs/openmm/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/ccs/home/jdakka/.conda/envs/openmm/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 235, in _simulate
    self._generate_reports(unwrapped, False)
  File "/ccs/home/jdakka/.conda/envs/openmm/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 254, in _generate_reports
    reporter.report(self, state)
  File "/ccs/home/jdakka/.conda/envs/openmm/lib/python2.7/site-packages/simtk/openmm/app/checkpointreporter.py", line 127, in report
    os.rename(tempFilename1, self._file)
OSError: [Errno 2] No such file or directory
```

But that file indeed exists: 

```
bash-4.2$ ls /ccs/home/jdakka/.conda/envs/openmm/lib/python2.7/site-packages/simtk/openmm/app/
__init__.py	     charmmcrdfiles.pyc      data		 element.py	     gromacstopfile.pyc  pdbreporter.pyc	topology.py
__init__.pyc	     charmmparameterset.py   dcdfile.py		 element.pyc	     internal		 pdbxfile.py		topology.pyc
amberinpcrdfile.py   charmmparameterset.pyc  dcdfile.pyc	 forcefield.py	     modeller.py	 pdbxfile.pyc
amberinpcrdfile.pyc  charmmpsffile.py	     dcdreporter.py	 forcefield.pyc      modeller.pyc	 simulation.py
amberprmtopfile.py   charmmpsffile.pyc	     dcdreporter.pyc	 gromacsgrofile.py   pdbfile.py		 simulation.pyc
amberprmtopfile.pyc  checkpointreporter.py   desmonddmsfile.py	 gromacsgrofile.pyc  pdbfile.pyc	 statedatareporter.py
charmmcrdfiles.py    checkpointreporter.pyc  desmonddmsfile.pyc  gromacstopfile.py   pdbreporter.py	 statedatareporter.pyc
```

**Comment by hengma1001** [comment]
A brief test of OpenMM check point: 

1. Error in input of checkpoint file. (No input check point)
```bash
[hm0@mds-lnx16 fs-pep]$ python run_openmm.py -f pdb/100-fs-peptide-400K.pdb -c checkpnt.chk
Traceback (most recent call last):
  File "run_openmm.py", line 41, in <module>
    sim_time=10000*u.nanoseconds)
  File "../MD_utils/openmm_simulation.py", line 230, in openmm_simulate_amber_fs_pep
    simulation.loadCheckpoint(check_point)
  File "/home/hm0/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 290, in loadCheckpoint
    with open(file, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/home/hm0/Research/CVAE_pilot_MD/hyperspace/microscope/experiments/MD_exps/fs-pep/checkpnt.chk'
```

2. Assign somewhere doesn't exist for OpenMM to write check point. 
```bash 
[hm0@mds-lnx16 fs-pep]$ python run_openmm.py -f pdb/100-fs-peptide-400K.pdb
Traceback (most recent call last):
  File "run_openmm.py", line 41, in <module>
    sim_time=10000*u.nanoseconds)
  File "../MD_utils/openmm_simulation.py", line 232, in openmm_simulate_amber_fs_pep
    simulation.step(nsteps)
  File "/home/hm0/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/hm0/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 235, in _simulate
    self._generate_reports(unwrapped, False)
  File "/home/hm0/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 254, in _generate_reports
    reporter.report(self, state)
  File "/home/hm0/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/checkpointreporter.py", line 122, in report
    with open(tempFilename1, 'w+b', 0) as out:
IOError: [Errno 2] No such file or directory: '~/fskfj/checkpnt.chk.backup1'
```

3. Using different GPU loading same check point. 
   No error. 

4. Test it on Summit.  
   Worked so far with simple direct simulation. 
```bash
#!/bin/bash
# Summitdev OpenMM testing
#BSUB -P 
#BSUB -J test_omm_ppc
#BSUB -o tst.o%J
#BSUB -W 1:00
#BSUB -nnodes 1
# End LSF directives and begin shell commands
date
source activate hm0
module load cuda/9.1.85
jsrun -n 1 -a 1 -g 1 python run_openmm.py -f pdb/100-fs-peptide-400K.pdb
```
